config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  resources :events do
  resources :attendances
  end

  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

	after_create :attendance_subs_mail_send

  def attendance_subs_mail_send
    AdminEventMailer.attendance_subs_mail(self).deliver_now
  end

	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord

	belongs_to :admin, class_name: "User"
	has_many :attendances
	has_many :users, through: :attendances

	validates :start_date, presence: true

	validates :duration, presence: true, numericality: { greater_than: 0 }

	validates :title, presence: true 
	# length: { in: 5..140 }

	validates :description, presence: true
	# , length: { in: 20..1000 }

	validates :price, presence: true
	# , numericality: { in: 1..1000 }

	validates :location, presence: true

	validate :multiple_of_5?
	validate :start_date_good?

	private

	def start_date_good?
		if start_date > Time.now
			true
		else
			errors.add(:start_date, "Ton event doit être dans le futur!")	
		end
	end

	def multiple_of_5?
		if duration%5 != 0
			errors.add(:duration, "La durée doit être un multiple de 5")
		end
	end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	# after_create :welcome_send

	# has_many :events, foreign_key: 'admin_id'
	has_many :attendances
	has_many :events, through: :attendances
	has_many :admins, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy

	# def welcome_send
 #    UserMailer.welcome_email(self).deliver_now
 #  end

 	#  def authenticate_current_user
  #   @user = User.find(params[:id])
  #   unless current_user == @user
  #     flash[:danger] = "Impossible d'aller sur cette page."
  #     redirect_to root_path
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
  end

  def show

  end

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    
     event = Event.find(params[:event_id])
     @attendance = Attendance.new(event: event, user: current_user, stripe_customer_id: params[:stripeEmail])

           # Amount in cents
    # unless event.is_free?
       @amount = event.price*100

       customer = Stripe::Customer.create({
                                            email: params[:stripeEmail],
                                            source: params[:stripeToken],
       })

       charge = Stripe::Charge.create({
                                        customer: customer.id,
                                        amount: @amount,
                                        description: 'Rails Stripe customer',
                                        currency: 'eur',
       })
    # end
     if @attendance.save
         flash[:success] = 'Tu as été enrgistré!'
     else
         flash[:danger] = 'There was a problem during the registration process'
     end
     redirect_to event_path(event.id)
   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to event_path(event.id)

  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def create

    puts "#"*60
    puts params
    puts "#"*60
    
    @event = Event.new(start_date:params[:start_date].to_datetime, duration:params[:duration], title:params[:title], description:params[:description], price:params[:price], location:params[:location], admin:current_user)

    if @event.save 

    flash[:success] = "Ton event qui déchire a été ajouté dans la liste!"
    redirect_to event_path(@event.id)

    else

    render 'new'

    end
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(duration:params[:duration], price:params[:price], location:params[:location])

        flash[:success] = "L'event a été édité!"
        redirect_to event_path
    else
      render :edit
    end

  end

  def destroy
    @event = Event.find(params[:id])

      if @event.destroy 
      flash[:success] = "Ton event a bien été supprimé!"
      redirect_to events_path   

      else
        render :destroy
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
   before_action :authenticate_user!, only: [:show, :edit, :update]
   before_action :user_signed_in?, except: [:show]
  def show
  	puts "#"*60
  	puts params
  	puts "#"*60
  	@user = current_user
    @events = @user.admins
  end

  def edit
    # @user = User.find(params[:id])
    
  end

  def update
    @user = User.find(params[:id])

    if @user.update(first_name:params[:first_name], last_name:params[:last_name], description:params[:description])

        flash[:success] = "Ton profil a été édité!"
        redirect_to user_path(@user.id)
    else
      render :edit
    end
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<% if @event.users.count != 0 %>

	<div class="container evinfo mx-auto">
	  <h3>Pour l'instant, tu as <%= @event.users.count %> participant(s)</h3>
	</div>

	<table class="table table-striped container">
	  <thead>
	    <tr>
	    	<th scope="col"></th>
	      <th scope="col">Nom</th>
	      <th scope="col">Adresse mail</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  	 <% i = 1 %>
	    <% @event.users.each do |user| %> 
	        <tr>
	          <th scope="row"><%= i %></th>
	            <td> <%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id) %> </td>
	            <td> <%= user.email %> </td>
	            <td> <%= link_to "Voir le profil du participant", user_path(user.id) %> </td>
	            <%i += 1 %>
	          </th>
	        </tr>
	    <% end %>
	  </tbody>
	</table>

<% else %>

	<div class="container evinfo mx-auto">
	  <h3>Désolé... aucun participant pour l'instant... </h3>
	  <h3>Va falloir faire de la com! </h3>
	</div>

<% end %>

<div class="container-fluid">
	  <div class="button-show">
	    <div class="button">
	      <a href="<%= edit_event_path(@event.id)%>" class="btn btn-warning btn-lg"> Editer l'event </a>
	    </div>
	    <div class="button">
	      <a class="btn btn-warning btn-lg" <%= link_to "Supprimer l'event", event_path(@event.id), :method => "delete" %> </a>
	    </div>
	  </div>
	</div>

app/views/attendances/new.html.erb
<div class="container evinfo mx-auto">
  <h3>Recapitulatif de l'event <%= @event.title%> avant règlement</h3>
</div>

<div class="container show">
  <div class="card mx-auto" style="width: 30rem">
    <div class="card-header">
      <h5 class="card-title"><%= @event.title %></h5>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= @event.description %>
      </li>
      <li class="list-group-item">Participants: <%= @event.users.count %>
      </li>  
      <li class="list-group-item">Organisateur: <%= @event.admin.email %>
      </li>
      <li class="list-group-item">Lieu: <%= @event.location%>
      </li>
      <li class="list-group-item">Prix: <%= @event.price%> euros
      </li>

    </ul>
  </div>
</div>

<div class="container pay">
	<%= form_tag url_for(action: 'create'), method: "post" do %>

		<article>
	    <% if flash[:error].present? %>
	      <div id="error_explanation">
	        <p><%= flash[:error] %></p>
	      </div>
	    <% end %>
	  </article>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	          data-description="A month's subscription"
	          data-amount= ""
	          data-locale="auto"></script>
	<% end %>
</div>

app/views/attendances/show.html.erb
<table class="table table-striped container">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nom</th>
      <th scope="col">Adresse mail</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% i = 1 %>
    <% @event.users.each do |user| %> 
        <tr>
          <th scope="row"><%= i %></th>
            <td> <%= user.first_name %> <%= user.last_name %> </td>
            <td> <%= user.email %> </td>
            <td> <%= link_to "Voir le profil du participant", user_path(user.id) %> </td>
            <%i += 1 %>
          </th>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container evinfo mx-auto">
  <h3>Bienvenue sur l'edit de ton event</h3>
  <div class="container">
	  <h5>Afin de ne pas trop perturber tes participants, tu ne peux modifier que la durée, le prix et le lieu de ton event</h5>
	  <h5>Pour toute autre modif, il est préférable de supprimer ton event et le crée à nouveau...</h5>
  </div>
</div>

<div class="form container">
	<%= form_tag url_for(action: 'update'), method: "patch" do %>
		
		<div class="form-group">
		  <%= label_tag 'Durée' %><br>
		  <%= text_field_tag 'duration'%>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Prix' %><br>
		  <%= text_field_tag 'price' %>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Lieu' %><br>
		  <%= text_field_tag 'location'%>
		  <br /> <br />
		</div>


	  <%= submit_tag "Edit l'event" %>

	 <% end %>
 </div>

app/views/events/index.html.erb
<!-- JUMBOTRON -->


<header>

<div class="jumbotron jumbotron-fluid">
  <div class="text">
    <h1 class="display-4">Better Eventbrite</h1>
    <p class="lead">Des sorties à n'en plus travailler...</p>
  </div>
</div>

</header>


<div class="button">
	<a class="btn btn-warning btn-lg" href="<%= new_event_path %>">Crée ton Event!
	</a>
</div>

<div class="container event">
	<div class="row">
		<% @events.each do |event, id| %>

			<div class="col-lg-4 ev">
				<%= image_tag("event.jpeg", :size => "240x240", :class => "rounded-circle") %>
				<div class="container evtxt">
			    <h5><%= link_to "#{event.title}", event_path(event.id)%></h5>
			    <p><%= event.start_date %> </p>
		  	</div>
			</div>

		<% end %>
	</div>
</div>

app/views/events/new.html.erb
 <div class="form container">
	<%= form_tag url_for(action: 'create'), method: "post" do %>
		
		<div class="form-group">
		  <%= label_tag 'Date' %><br>
		  <%= date_field_tag 'start_date' %>
		  <br /> <br />
		</div>
		
		<div class="form-group">
		  <%= label_tag 'Durée' %><br>
		  <%= text_field_tag 'duration'%>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Title' %><br>
		  <%= text_field_tag 'title' %>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Description' %><br>
		  <%= text_field_tag 'description'%>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Prix' %><br>
		  <%= text_field_tag 'price' %>
		  <br /> <br />
		</div>

		<div class="form-group">
		  <%= label_tag 'Lieu' %><br>
		  <%= text_field_tag 'location'%>
		  <br /> <br />
		</div>


	  <%= submit_tag "Crée ton event" %>

	 <% end %>
 </div>

app/views/events/show.html.erb
<div class="container evinfo mx-auto">
  <h3>Event proposé par <%= @event.admin.first_name%></h3>
</div>

<div class="container show">
  <div class="card mx-auto" style="width: 30rem">
    <div class="card-header">
      <h5 class="card-title"><%= @event.title %></h5>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= @event.description %>
      </li>
      <li class="list-group-item">Participants: <%= @event.users.count %>
      </li>  
      <li class="list-group-item">Organisateur: <%= @event.admin.email %>
      </li>
      <li class="list-group-item">Lieu: <%= @event.location%>
      </li>
      <li class="list-group-item">Prix: <%= @event.price%> euros
      </li>

    </ul>
  </div>
</div>


<% if current_user != @event.admin && @event.users.include?(current_user) == false %>

    <div class="button">
      <a href="<%= new_event_attendance_path(@event.id) %>" class="btn btn-warning btn-lg"> Participer </a>
    </div>
<% end %>

<% if current_user == @event.admin %>

  <div class="button">
    <a href="<%= event_attendances_path(@event.id) %>" class="btn btn-warning btn-lg">Mon espace event </a>
  </div>
<% end %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Better Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

       <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> 

  </head>
  
  <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="<%= events_path%>" class="navbar-brand">Better Eventbrite </a>
        <!-- lien alternatif pour garder la class="navbar..." vers le page /home-->

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a href="<%= events_path%>" class="nav-item nav-link active">Les Events
            </a>
            <a href="<%= new_event_path%>" class="nav-item nav-link active">Crée ton Event!
            </a>
          </div>
        </div>


        <% if user_signed_in? %>
        
          <div class="profil">
            <form class="form-inline my-2 my-lg-0">
              <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Ton profil
                </button>
                
                  <div class="dropdown-menu">

                    <p><%= link_to "Ton profil", user_path(current_user.id) %></p>
                    <p> <%= link_to "Deconnecte-toi", destroy_user_session_path, method: :delete %></p>
                  </div>
              
              </div>
            </form>
         </div>
        
        <% else %>

          <div class="profil">
            <form class="form-inline my-2 my-lg-0">
              <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Crée ton compte/Connecte-toi
                </button>
                
                  <div class="dropdown-menu">
                    <p><%= link_to "Crée ton compte", new_user_registration_path %></p>
                    <p> <%= link_to "Connecte-toi", new_user_session_path %></p>
                  </div>
              
              </div>
            </form>
          </div>

        <% end %>  

      </nav>
  </header>

  <body>

  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

      <%= yield %>

 
  </body>
</html>

app/views/users/edit.html.erb
<div class="container evinfo mx-auto">
  <h3>Bienvenue sur l'edit de ton profil</h3>
  <div class="container">
    <h5>Tu peux enfin mettre ton nom et ton prénom, plus sympa pour les utilisateurs!</h5>
  </div>
</div>

<div class="form container">
  <%= form_tag url_for(action: 'update'), method: "patch" do %>
    
    <div class="form-group">
      <%= label_tag 'Ton nom' %><br>
      <%= text_field_tag 'last_name'%>
      <br /> <br />
    </div>

    <div class="form-group">
      <%= label_tag 'Ton prénom' %><br>
      <%= text_field_tag 'first_name' %>
      <br /> <br />
    </div>

    <div class="form-group">
      <%= label_tag 'Un pti topo sur toi' %><br>
      <%= text_field_tag 'description'%>
      <br /> <br />
    </div>


    <%= submit_tag "Edit ton profil" %>

   <% end %>
 </div>

app/views/users/show.html.erb
<div class="container evinfo mx-auto">
  <h3>Bienvenue <%= @user.first_name %> sur ton profil</h3>
</div>

<div class="container show">

  <div class="card mx-auto" style="width: 30rem">

    <div class="card-header">
      <h5 class="card-title"> Ton Profil</h5>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item">Prénom: <%= @user.first_name %>
      </li>
      <li class="list-group-item">Nom: <%= @user.last_name %>
      </li>  
      <li class="list-group-item">Description: <%= @user.description %>
      </li>
      <li class="list-group-item">Email: <%= @user.email %>
      </li>

    </ul>
  </div>
</div>

<% if @user == current_user %>
<div class="container-fluid">
  <div class="button-show butprof">
    <div class="button">
      <a href="<%= edit_user_path(current_user.id)%>" class="btn btn-warning btn-lg"> Editer mon profil </a>
    </div>
    <div class="button">
      <a href="<%= edit_user_registration_path %>" class="btn btn-warning btn-lg">Modifier mon email et/ou mon mot de passe </a>
    </div>
  </div>
</div>

  <% if @events != nil %>

    <div class="container event">
      <div class="row">
        <% @events.each do |event| %>

          <div class="col-lg-4 ev">
            <%= image_tag("event.jpeg", :size => "240x240", :class => "rounded-circle") %>
            <div class="container evtxt">
              <h5><%= link_to "#{event.title}", event_path(event.id)%></h5>
              <p><%= event.start_date %> </p>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  <% else %>

   <h5 class="card-title">Tu n'as pas encore créé d'event!</h5>

  <% end %>
<% end %>




  
 